blank_issues_enabled: true
contact_links:
  - name: 🏎️ Conhecer o Fórmula Tech Lead
    url: https://formulatechlead.com.br/
    about: Conheça o programa para desenvolver sua liderança técnica.
  - name: 🎥 Inscreva-se no YouTube
    url: https://www.youtube.com/@brunocaetanobrito?sub_confirmation=1
    about: Acompanhe conteúdos sobre tecnologia, GitHub Copilot, DevOps e carreira.
